from django.db import models


# def get_default_action_status():
#     """ sets a default value for mobile number;
#     create new user if not available """
#     # print(NewUser.objects.get_or_create(userMobile=0))
#     return NewUser.objects.get_or_create(userMobile=0)[0]


class NewUser(models.Model):
    '''
    userName -> name of the user
    userId -> id of the user -> generated by Django
    userMobile (unique) -> mobile number for the user,
    '''
    userName = models.CharField(max_length=50)
    userMobile = models.IntegerField(unique=True)

    def __str__(self):
        return str(self.userMobile)


class Car(models.Model):

    '''
    carLicenseNumber -> liscence plate number for the car,
    Manufacturer -> name of the manufacturer,
    Model -> city,
    base_price -> Base price for any KM,
    pph -> price per hour ,
    security_deposit -> security deposit for the car
    '''
    carLicenseNumber = models.CharField(max_length=30, unique=True)
    Manufacturer = models.CharField(max_length=40)
    Model = models.CharField(max_length=40)
    base_price = models.IntegerField()
    pph = models.IntegerField()
    security_deposit = models.IntegerField()

    def __str__(self):
        return self.carLicenseNumber


class BookedCars(models.Model):
    userid = models.ForeignKey(NewUser, on_delete=models.CASCADE)
    toDate = models.DateTimeField()
    fromDate = models.DateTimeField()
    carLicenseNumber = models.ForeignKey(
        Car, on_delete=models.CASCADE)
