# Generated by Django 3.1.5 on 2021-03-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('carLicenseNumber', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('Manufacturer', models.CharField(max_length=40)),
                ('Model', models.CharField(max_length=40)),
                ('base_price', models.IntegerField()),
                ('pph', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('userName', models.CharField(max_length=50)),
                ('userMobile', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookedCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toDate', models.DateTimeField()),
                ('fromDate', models.DateTimeField()),
                ('carLicenseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApi.car')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarApi.newuser')),
            ],
        ),
    ]
